//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALD.LibFiscalCode.Localization {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodiceFiscaleUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodiceFiscaleUI() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALD.LibFiscalCode.Localization.CodiceFiscaleUI", typeof(CodiceFiscaleUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni su Codice Fiscale.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Archivio.
        /// </summary>
        public static string ArchiveWindowTitle {
            get {
                return ResourceManager.GetString("ArchiveWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Calcola.
        /// </summary>
        public static string BtnCalculate {
            get {
                return ResourceManager.GetString("BtnCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string BtnCancel1 {
            get {
                return ResourceManager.GetString("BtnCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiudi.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chiudi la finestra senza selezionare un luogo.
        /// </summary>
        public static string BtnCloseTooltip {
            get {
                return ResourceManager.GetString("BtnCloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma.
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copia.
        /// </summary>
        public static string BtnCopyToClipboard {
            get {
                return ResourceManager.GetString("BtnCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sovrascrivi.
        /// </summary>
        public static string BtnOverwrite {
            get {
                return ResourceManager.GetString("BtnOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona.
        /// </summary>
        public static string BtnSelectPlace {
            get {
                return ResourceManager.GetString("BtnSelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Importa.
        /// </summary>
        public static string BtnStartImport {
            get {
                return ResourceManager.GetString("BtnStartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiorna.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The input parameter must be a string 15 characters long.
        /// </summary>
        public static string BuilderPartialFcLengthException {
            get {
                return ResourceManager.GetString("BuilderPartialFcLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abilita.
        /// </summary>
        public static string ChkEnableCustMapping {
            get {
                return ResourceManager.GetString("ChkEnableCustMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Byte[].
        /// </summary>
        public static byte[] codicefiscale_icopng {
            get {
                object obj = ResourceManager.GetObject("codicefiscale_icopng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copia.
        /// </summary>
        public static string CtxMnuCopy {
            get {
                return ResourceManager.GetString("CtxMnuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Imposta come principale.
        /// </summary>
        public static string CtxMnuLstOmocode {
            get {
                return ResourceManager.GetString("CtxMnuLstOmocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona una data.
        /// </summary>
        public static string DatePickerWindowTitle {
            get {
                return ResourceManager.GetString("DatePickerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma uscita.
        /// </summary>
        public static string DialogConfirmExitCaption {
            get {
                return ResourceManager.GetString("DialogConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai delle modifiche in sospeso che verranno perse se esci dall&apos;applicazione. Sei sicuro?.
        /// </summary>
        public static string DialogConfirmExitText {
            get {
                return ResourceManager.GetString("DialogConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante l&apos;apertura.
        /// </summary>
        public static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è stato possibile aprire il file {0}.
        /// </summary>
        public static string ErrorDialogText {
            get {
                return ResourceManager.GetString("ErrorDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File JSON | (*.json).
        /// </summary>
        public static string ExportDialogJsonFilter {
            get {
                return ResourceManager.GetString("ExportDialogJsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esporta in formato JSON.
        /// </summary>
        public static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File XML | (*.xml).
        /// </summary>
        public static string ExportDialogXmlFilter {
            get {
                return ResourceManager.GetString("ExportDialogXmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona la posizione del file di dati.
        /// </summary>
        public static string FileDialogDatabaseFile {
            get {
                return ResourceManager.GetString("FileDialogDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del sesso e della data di nascita non è valida..
        /// </summary>
        public static string FiscalCodeValidationBirthDateAndGenderInvalid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationBirthDateAndGenderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nel codice fiscale la data di nascita e il sesso sono rappresentati da una stringa di cinque caratteri, calcolata nel modo seguente:\nSi prende la data di nascita in formato YYMMDD e si sostituisce il mese in base a una regola di sostituzione. Se il soggetto è di sesso femminile, si aggiunge 40 al giorno di nascita.\nLa rappresentazione della data di nascita e del sesso prevista era {0}..
        /// </summary>
        public static string FiscalCodeValidationBirthDateAndGenderInvalidDetails {
            get {
                return ResourceManager.GetString("FiscalCodeValidationBirthDateAndGenderInvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del sesso e della data di nascita è valida..
        /// </summary>
        public static string FiscalCodeValidationBirthDateAndGenderValid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationBirthDateAndGenderValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La check digit non è valida..
        /// </summary>
        public static string FiscalCodeValidationCheckDigitInvalid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationCheckDigitInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La check digit è un carattere che viene calcolato in base ai precedenti quindici caratteri secondo un algoritmo specifico. La check digit prevista era {0}..
        /// </summary>
        public static string FiscalCodeValidationCheckDigitInvalidDetails {
            get {
                return ResourceManager.GetString("FiscalCodeValidationCheckDigitInvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La check digit è valida..
        /// </summary>
        public static string FiscalCodeValidationCheckDigitValid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationCheckDigitValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del nome non è valida..
        /// </summary>
        public static string FiscalCodeValidationNameInvalid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nel codice fiscale il nome viene rappresentato da una stringa di tre caratteri, calcolata nel modo seguente:\nSe il nome contiene più di quattro consonanti, vengono prese la prima, la terza e la quarta consonante.\nAltrimenti, vengono applicate le stesse regole usate per il cognome.\nLa rappresentazione del nome prevista era {0}..
        /// </summary>
        public static string FiscalCodeValidationNameInvalidDetails {
            get {
                return ResourceManager.GetString("FiscalCodeValidationNameInvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del nome è valida..
        /// </summary>
        public static string FiscalCodeValidationNameValid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il codice del luogo non è valido..
        /// </summary>
        public static string FiscalCodeValidationPlaceCodeInvalid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationPlaceCodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nel codice fiscale il luogo di nascita è rappresentato dal codice nazionale o Codice Belfiore, una stringa di 4 caratteri alfanumerici composta da una lettera e tre numeri. Il codice Belfiore previsto per questo codice fiscale era {0}..
        /// </summary>
        public static string FiscalCodeValidationPlaceCodeInvalidDetails {
            get {
                return ResourceManager.GetString("FiscalCodeValidationPlaceCodeInvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il codice del luogo è valido..
        /// </summary>
        public static string FiscalCodeValidationPlaceCodeValid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationPlaceCodeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del cognome non è valida..
        /// </summary>
        public static string FiscalCodeValidationSurnameInvalid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationSurnameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nel codice fiscale il cognome viene rappresentato da una stringa di tre caratteri, calcolata nel modo seguente:\nSe il cognome contiene più di tre consonanti, vengono prese la prima, la seconda e la terza consonante.\nAltrimenti, vengono prese le consonanti presenti e si popolano le lettere mancanti con le vocali nell&apos;ordine in cui compaiono. Se anche in questo caso la lunghezza della stringa risultante è inferiore ai tre caratteri, l&apos;ultimo carattere viene posto fisso a X.\nLa rappresentazione del cognome  [stringa troncata]&quot;;.
        /// </summary>
        public static string FiscalCodeValidationSurnameInvalidDetails {
            get {
                return ResourceManager.GetString("FiscalCodeValidationSurnameInvalidDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La rappresentazione del cognome è valida..
        /// </summary>
        public static string FiscalCodeValidationSurnameValid {
            get {
                return ResourceManager.GetString("FiscalCodeValidationSurnameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mapping personalizzato.
        /// </summary>
        public static string GrpBxCustomMapping {
            get {
                return ResourceManager.GetString("GrpBxCustomMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codici fiscali.
        /// </summary>
        public static string GrpBxFiscalCodes {
            get {
                return ResourceManager.GetString("GrpBxFiscalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni.
        /// </summary>
        public static string GrpBxInformation {
            get {
                return ResourceManager.GetString("GrpBxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità.
        /// </summary>
        public static string GrpBxMode {
            get {
                return ResourceManager.GetString("GrpBxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni personali.
        /// </summary>
        public static string GrpBxPersonalInfo {
            get {
                return ResourceManager.GetString("GrpBxPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luoghi.
        /// </summary>
        public static string GrpBxPlaces {
            get {
                return ResourceManager.GetString("GrpBxPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data di nascita.
        /// </summary>
        public static string HdrDateOfBirth {
            get {
                return ResourceManager.GetString("HdrDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Corrisponde a.
        /// </summary>
        public static string HdrFieldMapsTo {
            get {
                return ResourceManager.GetString("HdrFieldMapsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string HdrFieldName {
            get {
                return ResourceManager.GetString("HdrFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posizione.
        /// </summary>
        public static string HdrFieldPosition {
            get {
                return ResourceManager.GetString("HdrFieldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice fiscale.
        /// </summary>
        public static string HdrFiscalCode {
            get {
                return ResourceManager.GetString("HdrFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sesso.
        /// </summary>
        public static string HdrGender {
            get {
                return ResourceManager.GetString("HdrGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string HdrName {
            get {
                return ResourceManager.GetString("HdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luogo di nascita.
        /// </summary>
        public static string HdrPlaceOfBirth {
            get {
                return ResourceManager.GetString("HdrPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string HdrSurname {
            get {
                return ResourceManager.GetString("HdrSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Abbreviazione:.
        /// </summary>
        public static string LblAbbreviation {
            get {
                return ResourceManager.GetString("LblAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice:.
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Posizione database.
        /// </summary>
        public static string LblDatabasePath {
            get {
                return ResourceManager.GetString("LblDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data di nascita.
        /// </summary>
        public static string LblDateOfBirth {
            get {
                return ResourceManager.GetString("LblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data predefinita.
        /// </summary>
        public static string LblDefaultDate {
            get {
                return ResourceManager.GetString("LblDefaultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sesso.
        /// </summary>
        public static string LblGender {
            get {
                return ResourceManager.GetString("LblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lingua.
        /// </summary>
        public static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dimensione cronologia.
        /// </summary>
        public static string LblMaxHistorySize {
            get {
                return ResourceManager.GetString("LblMaxHistorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome:.
        /// </summary>
        public static string LblPlaceName {
            get {
                return ResourceManager.GetString("LblPlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luogo di nascita.
        /// </summary>
        public static string LblPlaceOfBirth {
            get {
                return ResourceManager.GetString("LblPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Provincia:.
        /// </summary>
        public static string LblProvince {
            get {
                return ResourceManager.GetString("LblProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regione:.
        /// </summary>
        public static string LblRegion {
            get {
                return ResourceManager.GetString("LblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca.
        /// </summary>
        public static string LblSearch {
            get {
                return ResourceManager.GetString("LblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File di origine.
        /// </summary>
        public static string LblSourceFile {
            get {
                return ResourceManager.GetString("LblSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Metodo di splitting.
        /// </summary>
        public static string LblSplittingStrategy {
            get {
                return ResourceManager.GetString("LblSplittingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string LblSurname {
            get {
                return ResourceManager.GetString("LblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice Fiscale.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni su Codice Fiscale.
        /// </summary>
        public static string MnuAbout {
            get {
                return ResourceManager.GetString("MnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avanzate.
        /// </summary>
        public static string MnuAdvanced {
            get {
                return ResourceManager.GetString("MnuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Archivio.
        /// </summary>
        public static string MnuArchive {
            get {
                return ResourceManager.GetString("MnuArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esporta.
        /// </summary>
        public static string MnuExport {
            get {
                return ResourceManager.GetString("MnuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In formato JSON.
        /// </summary>
        public static string MnuExportToJson {
            get {
                return ResourceManager.GetString("MnuExportToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a In formato XML.
        /// </summary>
        public static string MnuExportToXml {
            get {
                return ResourceManager.GetString("MnuExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File.
        /// </summary>
        public static string MnuFile {
            get {
                return ResourceManager.GetString("MnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ?.
        /// </summary>
        public static string MnuHelp {
            get {
                return ResourceManager.GetString("MnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo.
        /// </summary>
        public static string MnuNew {
            get {
                return ResourceManager.GetString("MnuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opzioni.
        /// </summary>
        public static string MnuOptions {
            get {
                return ResourceManager.GetString("MnuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco dei luoghi.
        /// </summary>
        public static string MnuPlaces {
            get {
                return ResourceManager.GetString("MnuPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esci.
        /// </summary>
        public static string MnuQuit {
            get {
                return ResourceManager.GetString("MnuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiorna database dei luoghi.
        /// </summary>
        public static string MnuUpdatePlaces {
            get {
                return ResourceManager.GetString("MnuUpdatePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valid parameter range 1-12.
        /// </summary>
        public static string MonthOfDateRangeError {
            get {
                return ResourceManager.GetString("MonthOfDateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non supportato!.
        /// </summary>
        public static string MsgBoxCopyNotSupportedCaption {
            get {
                return ResourceManager.GetString("MsgBoxCopyNotSupportedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copiare più codici fiscali non è un&apos;operazione supportata!.
        /// </summary>
        public static string MsgBoxCopyNotSupportedText {
            get {
                return ResourceManager.GetString("MsgBoxCopyNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impossibile esportare.
        /// </summary>
        public static string MsgBoxExportUnavailableCaption {
            get {
                return ResourceManager.GetString("MsgBoxExportUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è possibile esportare perché non hai ancora calcolato un codice fiscale..
        /// </summary>
        public static string MsgBoxExportUnavailableText {
            get {
                return ResourceManager.GetString("MsgBoxExportUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzionalità non disponibile!.
        /// </summary>
        public static string MsgBoxFeatureUnavailableCaption {
            get {
                return ResourceManager.GetString("MsgBoxFeatureUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La funzionalità richiesta non è ancora disponibile..
        /// </summary>
        public static string MsgBoxFeatureUnavailableText {
            get {
                return ResourceManager.GetString("MsgBoxFeatureUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File non valido.
        /// </summary>
        public static string MsgBoxInvalidDatabaseCaption {
            get {
                return ResourceManager.GetString("MsgBoxInvalidDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Il file non è un database di Codice Fiscale valido.\nLa posizione del database non è stata cambiata..
        /// </summary>
        public static string MsgBoxInvalidDatabaseText {
            get {
                return ResourceManager.GetString("MsgBoxInvalidDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifiche in sospeso.
        /// </summary>
        public static string MsgBoxPendingChangesCaption {
            get {
                return ResourceManager.GetString("MsgBoxPendingChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai delle modifiche in sospeso. Sei sicuro di voler uscire senza applicarle?.
        /// </summary>
        public static string MsgBoxPendingChangesText {
            get {
                return ResourceManager.GetString("MsgBoxPendingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma.
        /// </summary>
        public static string MsgBoxResetCaption {
            get {
                return ResourceManager.GetString("MsgBoxResetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai delle modifiche in sospeso. Sei sicuro di voler reimpostare?.
        /// </summary>
        public static string MsgBoxResetText {
            get {
                return ResourceManager.GetString("MsgBoxResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Conferma eliminazione.
        /// </summary>
        public static string MsgDeleteCaption {
            get {
                return ResourceManager.GetString("MsgDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei sicuro di voler eliminare gli elementi selezionati?.
        /// </summary>
        public static string MsgDeleteTextPlural {
            get {
                return ResourceManager.GetString("MsgDeleteTextPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sei sicuro di voler eliminare l&apos;elemento selezionato?.
        /// </summary>
        public static string MsgDeleteTextSingular {
            get {
                return ResourceManager.GetString("MsgDeleteTextSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a csv.
        /// </summary>
        public static string OpenFileDialogDefaultExt {
            get {
                return ResourceManager.GetString("OpenFileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valori separati da virgola(*.csv)|*.csv.
        /// </summary>
        public static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegli il file CSV di origine.
        /// </summary>
        public static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Importa dati nel DB.
        /// </summary>
        public static string PlacesImportViewTitle {
            get {
                return ResourceManager.GetString("PlacesImportViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona il luogo di nascita.
        /// </summary>
        public static string PlacesListTitle {
            get {
                return ResourceManager.GetString("PlacesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Opzioni.
        /// </summary>
        public static string SettingsWindowBanner {
            get {
                return ResourceManager.GetString("SettingsWindowBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Veloce.
        /// </summary>
        public static string SplittingMethodFast {
            get {
                return ResourceManager.GetString("SplittingMethodFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utilizza il metodo rapido di processamento dei caratteri. Migliora le performance ma non è in grado di eseguire la translitterazione automatica da altri alfabeti..
        /// </summary>
        public static string SplittingMethodFastTooltip {
            get {
                return ResourceManager.GetString("SplittingMethodFastTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unidecode.
        /// </summary>
        public static string SplittingMethodUnidecode {
            get {
                return ResourceManager.GetString("SplittingMethodUnidecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utilizza il metodo Unidecode per il processamento dei caratteri. È più lento e utilizza più memoria, ma è in grado di eseguire la traslitterazione automatica da altri alfabeti..
        /// </summary>
        public static string SplittingMethodUnidecodeTooltip {
            get {
                return ResourceManager.GetString("SplittingMethodUnidecodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Filtra i risultati....
        /// </summary>
        public static string TxtFilterResults {
            get {
                return ResourceManager.GetString("TxtFilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a L&apos;oggetto era null..
        /// </summary>
        public static string ValidationArgumentNull {
            get {
                return ResourceManager.GetString("ValidationArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di convalida.
        /// </summary>
        public static string ValidationDialogCaption {
            get {
                return ResourceManager.GetString("ValidationDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data di nascita non specificata.
        /// </summary>
        public static string ValidationMissingDateOfBirth {
            get {
                return ResourceManager.GetString("ValidationMissingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sesso non compilato..
        /// </summary>
        public static string ValidationMissingGender {
            get {
                return ResourceManager.GetString("ValidationMissingGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome non compilato..
        /// </summary>
        public static string ValidationMissingName {
            get {
                return ResourceManager.GetString("ValidationMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Luogo di nascita non specificato..
        /// </summary>
        public static string ValidationMissingPlaceOfBirth {
            get {
                return ResourceManager.GetString("ValidationMissingPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome non compilato..
        /// </summary>
        public static string ValidationMissingSurname {
            get {
                return ResourceManager.GetString("ValidationMissingSurname", resourceCulture);
            }
        }
    }
}
