//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALD.LibFiscalCode.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALD.LibFiscalCode.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni su Codice Fiscale.
        /// </summary>
        public static string AboutWindowTitle {
            get {
                return ResourceManager.GetString("AboutWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivio.
        /// </summary>
        public static string ArchiveWindowTitle {
            get {
                return ResourceManager.GetString("ArchiveWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calcola.
        /// </summary>
        public static string BtnCalculate {
            get {
                return ResourceManager.GetString("BtnCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulla.
        /// </summary>
        public static string BtnCancel1 {
            get {
                return ResourceManager.GetString("BtnCancel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiudi la finestra senza selezionare un luogo.
        /// </summary>
        public static string BtnCloseTooltip {
            get {
                return ResourceManager.GetString("BtnCloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        public static string BtnConfirm {
            get {
                return ResourceManager.GetString("BtnConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        public static string BtnCopyToClipboard {
            get {
                return ResourceManager.GetString("BtnCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sovrascrivi.
        /// </summary>
        public static string BtnOverwrite {
            get {
                return ResourceManager.GetString("BtnOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona.
        /// </summary>
        public static string BtnSelectPlace {
            get {
                return ResourceManager.GetString("BtnSelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa.
        /// </summary>
        public static string BtnStartImport {
            get {
                return ResourceManager.GetString("BtnStartImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input parameter must be a string 15 characters long.
        /// </summary>
        public static string BuilderPartialFcLengthException {
            get {
                return ResourceManager.GetString("BuilderPartialFcLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilita.
        /// </summary>
        public static string ChkEnableCustMapping {
            get {
                return ResourceManager.GetString("ChkEnableCustMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] codicefiscale_icopng {
            get {
                object obj = ResourceManager.GetObject("codicefiscale_icopng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copia.
        /// </summary>
        public static string CtxMnuCopy {
            get {
                return ResourceManager.GetString("CtxMnuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposta come principale.
        /// </summary>
        public static string CtxMnuLstOmocode {
            get {
                return ResourceManager.GetString("CtxMnuLstOmocode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona una data.
        /// </summary>
        public static string DatePickerWindowTitle {
            get {
                return ResourceManager.GetString("DatePickerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma uscita.
        /// </summary>
        public static string DialogConfirmExitCaption {
            get {
                return ResourceManager.GetString("DialogConfirmExitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai delle modifiche in sospeso che verranno perse se esci dall&apos;applicazione. Sei sicuro?.
        /// </summary>
        public static string DialogConfirmExitText {
            get {
                return ResourceManager.GetString("DialogConfirmExitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore durante l&apos;apertura.
        /// </summary>
        public static string ErrorDialogCaption {
            get {
                return ResourceManager.GetString("ErrorDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è stato possibile aprire il file {0}.
        /// </summary>
        public static string ErrorDialogText {
            get {
                return ResourceManager.GetString("ErrorDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File JSON | (*.json).
        /// </summary>
        public static string ExportDialogJsonFilter {
            get {
                return ResourceManager.GetString("ExportDialogJsonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esporta in formato JSON.
        /// </summary>
        public static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File XML | (*.xml).
        /// </summary>
        public static string ExportDialogXmlFilter {
            get {
                return ResourceManager.GetString("ExportDialogXmlFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona la posizione del file di dati.
        /// </summary>
        public static string FileDialogDatabaseFile {
            get {
                return ResourceManager.GetString("FileDialogDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping personalizzato.
        /// </summary>
        public static string GrpBxCustomMapping {
            get {
                return ResourceManager.GetString("GrpBxCustomMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codici fiscali.
        /// </summary>
        public static string GrpBxFiscalCodes {
            get {
                return ResourceManager.GetString("GrpBxFiscalCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni.
        /// </summary>
        public static string GrpBxInformation {
            get {
                return ResourceManager.GetString("GrpBxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalità.
        /// </summary>
        public static string GrpBxMode {
            get {
                return ResourceManager.GetString("GrpBxMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni personali.
        /// </summary>
        public static string GrpBxPersonalInfo {
            get {
                return ResourceManager.GetString("GrpBxPersonalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luoghi.
        /// </summary>
        public static string GrpBxPlaces {
            get {
                return ResourceManager.GetString("GrpBxPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di nascita.
        /// </summary>
        public static string HdrDateOfBirth {
            get {
                return ResourceManager.GetString("HdrDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrisponde a.
        /// </summary>
        public static string HdrFieldMapsTo {
            get {
                return ResourceManager.GetString("HdrFieldMapsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string HdrFieldName {
            get {
                return ResourceManager.GetString("HdrFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione.
        /// </summary>
        public static string HdrFieldPosition {
            get {
                return ResourceManager.GetString("HdrFieldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice fiscale.
        /// </summary>
        public static string HdrFiscalCode {
            get {
                return ResourceManager.GetString("HdrFiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesso.
        /// </summary>
        public static string HdrGender {
            get {
                return ResourceManager.GetString("HdrGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string HdrName {
            get {
                return ResourceManager.GetString("HdrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luogo di nascita.
        /// </summary>
        public static string HdrPlaceOfBirth {
            get {
                return ResourceManager.GetString("HdrPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string HdrSurname {
            get {
                return ResourceManager.GetString("HdrSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviazione:.
        /// </summary>
        public static string LblAbbreviation {
            get {
                return ResourceManager.GetString("LblAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice:.
        /// </summary>
        public static string LblCode {
            get {
                return ResourceManager.GetString("LblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posizione database.
        /// </summary>
        public static string LblDatabasePath {
            get {
                return ResourceManager.GetString("LblDatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di nascita.
        /// </summary>
        public static string LblDateOfBirth {
            get {
                return ResourceManager.GetString("LblDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data predefinita.
        /// </summary>
        public static string LblDefaultDate {
            get {
                return ResourceManager.GetString("LblDefaultDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesso.
        /// </summary>
        public static string LblGender {
            get {
                return ResourceManager.GetString("LblGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        public static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensione cronologia.
        /// </summary>
        public static string LblMaxHistorySize {
            get {
                return ResourceManager.GetString("LblMaxHistorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string LblPlaceName {
            get {
                return ResourceManager.GetString("LblPlaceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luogo di nascita.
        /// </summary>
        public static string LblPlaceOfBirth {
            get {
                return ResourceManager.GetString("LblPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provincia:.
        /// </summary>
        public static string LblProvince {
            get {
                return ResourceManager.GetString("LblProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regione:.
        /// </summary>
        public static string LblRegion {
            get {
                return ResourceManager.GetString("LblRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerca.
        /// </summary>
        public static string LblSearch {
            get {
                return ResourceManager.GetString("LblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File di origine.
        /// </summary>
        public static string LblSourceFile {
            get {
                return ResourceManager.GetString("LblSourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metodo di splitting.
        /// </summary>
        public static string LblSplittingStrategy {
            get {
                return ResourceManager.GetString("LblSplittingStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome.
        /// </summary>
        public static string LblSurname {
            get {
                return ResourceManager.GetString("LblSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Fiscale.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni su Codice Fiscale.
        /// </summary>
        public static string MnuAbout {
            get {
                return ResourceManager.GetString("MnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avanzate.
        /// </summary>
        public static string MnuAdvanced {
            get {
                return ResourceManager.GetString("MnuAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archivio.
        /// </summary>
        public static string MnuArchive {
            get {
                return ResourceManager.GetString("MnuArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esporta.
        /// </summary>
        public static string MnuExport {
            get {
                return ResourceManager.GetString("MnuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In formato JSON.
        /// </summary>
        public static string MnuExportToJson {
            get {
                return ResourceManager.GetString("MnuExportToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In formato XML.
        /// </summary>
        public static string MnuExportToXml {
            get {
                return ResourceManager.GetString("MnuExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MnuFile {
            get {
                return ResourceManager.GetString("MnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string MnuHelp {
            get {
                return ResourceManager.GetString("MnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string MnuNew {
            get {
                return ResourceManager.GetString("MnuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni.
        /// </summary>
        public static string MnuOptions {
            get {
                return ResourceManager.GetString("MnuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elenco dei luoghi.
        /// </summary>
        public static string MnuPlaces {
            get {
                return ResourceManager.GetString("MnuPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esci.
        /// </summary>
        public static string MnuQuit {
            get {
                return ResourceManager.GetString("MnuQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna database dei luoghi.
        /// </summary>
        public static string MnuUpdatePlaces {
            get {
                return ResourceManager.GetString("MnuUpdatePlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid parameter range 1-12.
        /// </summary>
        public static string MonthOfDateRangeError {
            get {
                return ResourceManager.GetString("MonthOfDateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non supportato!.
        /// </summary>
        public static string MsgBoxCopyNotSupportedCaption {
            get {
                return ResourceManager.GetString("MsgBoxCopyNotSupportedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiare più codici fiscali non è un&apos;operazione supportata!.
        /// </summary>
        public static string MsgBoxCopyNotSupportedText {
            get {
                return ResourceManager.GetString("MsgBoxCopyNotSupportedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossibile esportare.
        /// </summary>
        public static string MsgBoxExportUnavailableCaption {
            get {
                return ResourceManager.GetString("MsgBoxExportUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non è possibile esportare perché non hai ancora calcolato un codice fiscale..
        /// </summary>
        public static string MsgBoxExportUnavailableText {
            get {
                return ResourceManager.GetString("MsgBoxExportUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funzionalità non disponibile!.
        /// </summary>
        public static string MsgBoxFeatureUnavailableCaption {
            get {
                return ResourceManager.GetString("MsgBoxFeatureUnavailableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La funzionalità richiesta non è ancora disponibile..
        /// </summary>
        public static string MsgBoxFeatureUnavailableText {
            get {
                return ResourceManager.GetString("MsgBoxFeatureUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File non valido.
        /// </summary>
        public static string MsgBoxInvalidDatabaseCaption {
            get {
                return ResourceManager.GetString("MsgBoxInvalidDatabaseCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il file non è un database di Codice Fiscale valido.\nLa posizione del database non è stata cambiata..
        /// </summary>
        public static string MsgBoxInvalidDatabaseText {
            get {
                return ResourceManager.GetString("MsgBoxInvalidDatabaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiche in sospeso.
        /// </summary>
        public static string MsgBoxPendingChangesCaption {
            get {
                return ResourceManager.GetString("MsgBoxPendingChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai delle modifiche in sospeso. Sei sicuro di voler uscire senza applicarle?.
        /// </summary>
        public static string MsgBoxPendingChangesText {
            get {
                return ResourceManager.GetString("MsgBoxPendingChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma.
        /// </summary>
        public static string MsgBoxResetCaption {
            get {
                return ResourceManager.GetString("MsgBoxResetCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai delle modifiche in sospeso. Sei sicuro di voler reimpostare?.
        /// </summary>
        public static string MsgBoxResetText {
            get {
                return ResourceManager.GetString("MsgBoxResetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conferma eliminazione.
        /// </summary>
        public static string MsgDeleteCaption {
            get {
                return ResourceManager.GetString("MsgDeleteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare gli elementi selezionati?.
        /// </summary>
        public static string MsgDeleteTextPlural {
            get {
                return ResourceManager.GetString("MsgDeleteTextPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sei sicuro di voler eliminare l&apos;elemento selezionato?.
        /// </summary>
        public static string MsgDeleteTextSingular {
            get {
                return ResourceManager.GetString("MsgDeleteTextSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        public static string OpenFileDialogDefaultExt {
            get {
                return ResourceManager.GetString("OpenFileDialogDefaultExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valori separati da virgola(*.csv)|*.csv.
        /// </summary>
        public static string OpenFileDialogFilter {
            get {
                return ResourceManager.GetString("OpenFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli il file CSV di origine.
        /// </summary>
        public static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importa dati nel DB.
        /// </summary>
        public static string PlacesImportViewTitle {
            get {
                return ResourceManager.GetString("PlacesImportViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona il luogo di nascita.
        /// </summary>
        public static string PlacesListTitle {
            get {
                return ResourceManager.GetString("PlacesListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opzioni.
        /// </summary>
        public static string SettingsWindowBanner {
            get {
                return ResourceManager.GetString("SettingsWindowBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impostazioni.
        /// </summary>
        public static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veloce.
        /// </summary>
        public static string SplittingMethodFast {
            get {
                return ResourceManager.GetString("SplittingMethodFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizza il metodo rapido di processamento dei caratteri. Migliora le performance ma non è in grado di eseguire la translitterazione automatica da altri alfabeti..
        /// </summary>
        public static string SplittingMethodFastTooltip {
            get {
                return ResourceManager.GetString("SplittingMethodFastTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidecode.
        /// </summary>
        public static string SplittingMethodUnidecode {
            get {
                return ResourceManager.GetString("SplittingMethodUnidecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizza il metodo Unidecode per il processamento dei caratteri. È più lento e utilizza più memoria, ma è in grado di eseguire la traslitterazione automatica da altri alfabeti..
        /// </summary>
        public static string SplittingMethodUnidecodeTooltip {
            get {
                return ResourceManager.GetString("SplittingMethodUnidecodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtra i risultati....
        /// </summary>
        public static string TxtFilterResults {
            get {
                return ResourceManager.GetString("TxtFilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore di convalida.
        /// </summary>
        public static string ValidationDialogCaption {
            get {
                return ResourceManager.GetString("ValidationDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di nascita non specificata.
        /// </summary>
        public static string ValidationMissingDateOfBirth {
            get {
                return ResourceManager.GetString("ValidationMissingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sesso non compilato..
        /// </summary>
        public static string ValidationMissingGender {
            get {
                return ResourceManager.GetString("ValidationMissingGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome non compilato..
        /// </summary>
        public static string ValidationMissingName {
            get {
                return ResourceManager.GetString("ValidationMissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cognome non compilato..
        /// </summary>
        public static string ValidationMissingSurname {
            get {
                return ResourceManager.GetString("ValidationMissingSurname", resourceCulture);
            }
        }
    }
}
