// <auto-generated />
using System;
using ALD.LibFiscalCode.Persistence.ORM.MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ALD.LibFiscalCode.Persistence.Migrations.SqlServerData
{
    [DbContext(typeof(SqlServerDataContext))]
    [Migration("20201019172338_ProvinceFK")]
    partial class ProvinceFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnName("province_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceAbbreviation")
                        .HasColumnName("province_abbreviation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Region")
                        .HasColumnName("region_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EndDate");

                    b.HasIndex("ProvinceAbbreviation");

                    b.HasIndex("Region");

                    b.HasIndex("StartDate");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("places");
                });

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.ProvinceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnName("abbreviation")
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("province_mapping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AG",
                            Name = "Agrigento",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AL",
                            Name = "Alessandria",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "AN",
                            Name = "Ancona",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "AO",
                            Name = "Aosta",
                            RegionId = 19
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "AO",
                            Name = "Arezzo",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "AP",
                            Name = "Ascoli Piceno",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "AT",
                            Name = "Asti",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "AV",
                            Name = "Avellino",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "BA",
                            Name = "Bari",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "BT",
                            Name = "Barletta-Andria-Trani",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "BL",
                            Name = "Belluno",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "BN",
                            Name = "Benevento",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "BG",
                            Name = "Bergamo",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "BI",
                            Name = "Biella",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "BO",
                            Name = "Bologna",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "BZ",
                            Name = "Bolzano",
                            RegionId = 17
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "BS",
                            Name = "Brescia",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 18,
                            Abbreviation = "BR",
                            Name = "Brindisi",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 19,
                            Abbreviation = "CA",
                            Name = "Cagliari",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 20,
                            Abbreviation = "CL",
                            Name = "Caltanissetta",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 21,
                            Abbreviation = "CB",
                            Name = "Campobasso",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 22,
                            Abbreviation = "CE",
                            Name = "Caserta",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 23,
                            Abbreviation = "CT",
                            Name = "Catania",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 24,
                            Abbreviation = "CZ",
                            Name = "Catanzaro",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 25,
                            Abbreviation = "CH",
                            Name = "Chieti",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 26,
                            Abbreviation = "CO",
                            Name = "Como",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 27,
                            Abbreviation = "CS",
                            Name = "Cosenza",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 28,
                            Abbreviation = "CR",
                            Name = "Cremona",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 29,
                            Abbreviation = "KR",
                            Name = "Crotone",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 30,
                            Abbreviation = "CN",
                            Name = "Cuneo",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 31,
                            Abbreviation = "EN",
                            Name = "Enna",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 32,
                            Abbreviation = "FM",
                            Name = "Fermo",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 33,
                            Abbreviation = "FE",
                            Name = "Ferrara",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 34,
                            Abbreviation = "FI",
                            Name = "Firenze",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 35,
                            Abbreviation = "FG",
                            Name = "Foggia",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 36,
                            Abbreviation = "FC",
                            Name = "Forlì-Cesena",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 37,
                            Abbreviation = "FR",
                            Name = "Frosinone",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 38,
                            Abbreviation = "GE",
                            Name = "Genova",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 39,
                            Abbreviation = "GO",
                            Name = "Gorizia",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 40,
                            Abbreviation = "GR",
                            Name = "Grosseto",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 41,
                            Abbreviation = "IM",
                            Name = "Imperia",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 42,
                            Abbreviation = "IS",
                            Name = "Isernia",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 43,
                            Abbreviation = "AQ",
                            Name = "L'Aquila",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 44,
                            Abbreviation = "SP",
                            Name = "La Spezia",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 45,
                            Abbreviation = "LT",
                            Name = "Latina",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 46,
                            Abbreviation = "LE",
                            Name = "Lecce",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 47,
                            Abbreviation = "LC",
                            Name = "Lecco",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 48,
                            Abbreviation = "LI",
                            Name = "Livorno",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 49,
                            Abbreviation = "LO",
                            Name = "Lodi",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 50,
                            Abbreviation = "LU",
                            Name = "Lucca",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 51,
                            Abbreviation = "MC",
                            Name = "Macerata",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 52,
                            Abbreviation = "MN",
                            Name = "Mantova",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 53,
                            Abbreviation = "MS",
                            Name = "Massa-Carrara",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 54,
                            Abbreviation = "MT",
                            Name = "Matera",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 55,
                            Abbreviation = "ME",
                            Name = "Messina",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 56,
                            Abbreviation = "MI",
                            Name = "Milano",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 57,
                            Abbreviation = "MO",
                            Name = "Modena",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 58,
                            Abbreviation = "MB",
                            Name = "Monza e della Brianza",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 59,
                            Abbreviation = "NA",
                            Name = "Napoli",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 60,
                            Abbreviation = "NO",
                            Name = "Novara",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 61,
                            Abbreviation = "NU",
                            Name = "Nuoro",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 62,
                            Abbreviation = "OR",
                            Name = "Oristano",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 63,
                            Abbreviation = "PD",
                            Name = "Padova",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 64,
                            Abbreviation = "PA",
                            Name = "Palermo",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 65,
                            Abbreviation = "PR",
                            Name = "Parma",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 66,
                            Abbreviation = "PV",
                            Name = "Pavia",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 67,
                            Abbreviation = "PG",
                            Name = "Perugia",
                            RegionId = 18
                        },
                        new
                        {
                            Id = 68,
                            Abbreviation = "PU",
                            Name = "Pesaro e Urbino",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 69,
                            Abbreviation = "PE",
                            Name = "Pescara",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 70,
                            Abbreviation = "PC",
                            Name = "Piacenza",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 71,
                            Abbreviation = "PI",
                            Name = "Pisa",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 72,
                            Abbreviation = "PT",
                            Name = "Pistoia",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 73,
                            Abbreviation = "PN",
                            Name = "Pordenone",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 74,
                            Abbreviation = "PZ",
                            Name = "Potenza",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 75,
                            Abbreviation = "PO",
                            Name = "Prato",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 76,
                            Abbreviation = "RG",
                            Name = "Ragusa",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 77,
                            Abbreviation = "RA",
                            Name = "Ravenna",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 78,
                            Name = "Reggio Calabria",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 79,
                            Abbreviation = "RE",
                            Name = "Reggio Emilia",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 80,
                            Abbreviation = "RI",
                            Name = "Rieti",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 81,
                            Abbreviation = "RN",
                            Name = "Rimini",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 82,
                            Abbreviation = "RM",
                            Name = "Roma",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 83,
                            Abbreviation = "RO",
                            Name = "Rovigo",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 84,
                            Abbreviation = "SA",
                            Name = "Salerno",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 85,
                            Abbreviation = "SS",
                            Name = "Sassari",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 86,
                            Abbreviation = "SV",
                            Name = "Savona",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 87,
                            Abbreviation = "SI",
                            Name = "Siena",
                            RegionId = 16
                        },
                        new
                        {
                            Id = 88,
                            Abbreviation = "SR",
                            Name = "Siracusa",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 89,
                            Abbreviation = "SO",
                            Name = "Sondrio",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 90,
                            Abbreviation = "SU",
                            Name = "Sud Sardegna",
                            RegionId = 14
                        },
                        new
                        {
                            Id = 91,
                            Abbreviation = "TA",
                            Name = "Taranto",
                            RegionId = 13
                        },
                        new
                        {
                            Id = 92,
                            Abbreviation = "TE",
                            Name = "Teramo",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 93,
                            Abbreviation = "TR",
                            Name = "Terni",
                            RegionId = 18
                        },
                        new
                        {
                            Id = 94,
                            Abbreviation = "TO",
                            Name = "Torino",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 95,
                            Abbreviation = "TP",
                            Name = "Trapani",
                            RegionId = 15
                        },
                        new
                        {
                            Id = 96,
                            Abbreviation = "TN",
                            Name = "Trento",
                            RegionId = 17
                        },
                        new
                        {
                            Id = 97,
                            Abbreviation = "TV",
                            Name = "Treviso",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 98,
                            Abbreviation = "TS",
                            Name = "Trieste",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 99,
                            Abbreviation = "UD",
                            Name = "Udine",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 100,
                            Abbreviation = "VA",
                            Name = "Varese",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 101,
                            Abbreviation = "VE",
                            Name = "Venezia",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 102,
                            Abbreviation = "VB",
                            Name = "Verbano-Cusio-Ossola",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 103,
                            Abbreviation = "VC",
                            Name = "Vercelli",
                            RegionId = 12
                        },
                        new
                        {
                            Id = 104,
                            Abbreviation = "VR",
                            Name = "Verona",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 105,
                            Abbreviation = "VV",
                            Name = "Vibo Valentia",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 106,
                            Abbreviation = "VI",
                            Name = "Vicenza",
                            RegionId = 20
                        },
                        new
                        {
                            Id = 107,
                            Abbreviation = "VT",
                            Name = "Viterbo",
                            RegionId = 7
                        });
                });

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.RegionMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Id");

                    b.ToTable("region_mapping");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abruzzo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Basilicata"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Calabria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Campania"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Emilia-Romagna"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Friuli Venezia Giulia"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Lazio"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Liguria"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Lombardia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Marche"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Molise"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Piemonte"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Puglia"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sardegna"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sicilia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Toscana"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Trentino-Alto Adige"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Umbria"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Valle d'Aosta"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Veneto"
                        });
                });

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.ProvinceMapping", b =>
                {
                    b.HasOne("ALD.LibFiscalCode.Persistence.Models.RegionMapping", "Region")
                        .WithMany("Provinces")
                        .HasForeignKey("RegionId");
                });
#pragma warning restore 612, 618
        }
    }
}
