// <auto-generated />
using System;
using ALD.LibFiscalCode.Persistence.ORM.MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ALD.LibFiscalCode.Persistence.Migrations.SqlServerData
{
    [DbContext(typeof(SqlServerDataContext))]
    partial class SqlServerDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnName("end_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnName("province_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceAbbreviation")
                        .HasColumnName("province_abbreviation")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Region")
                        .HasColumnName("region_name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnName("start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnName("updated_on")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceAbbreviation");

                    b.HasIndex("Region");

                    b.HasIndex("UpdatedOn");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.ProvinceMapping", b =>
                {
                    b.Property<string>("Abbreviation")
                        .HasColumnName("abbreviation")
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("Abbreviation");

                    b.ToTable("ProvinceMapping");
                });

            modelBuilder.Entity("ALD.LibFiscalCode.Persistence.Models.RegionMapping", b =>
                {
                    b.Property<string>("ProvinceAbbreviation")
                        .HasColumnName("province_abbreviation")
                        .HasColumnType("VARCHAR(2)");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("ProvinceAbbreviation");

                    b.ToTable("RegionMapping");
                });
#pragma warning restore 612, 618
        }
    }
}
